version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - terraformImage="hashicorp/terraform:0.12.23"
      - docker pull $terraformImage
      - PROJ_NAME="$PROJETCT_NAME"
      - REPOSITORY_URI="$ECR_ADDRESS"
      - mkdir .aws && aws s3 cp s3://lab-fiap-rm38/instance-need/.aws/credentials .aws/ && aws s3 cp s3://lab-fiap-rm38/instance-need/.aws/config .aws/
      - mkdir .ssh && aws s3 cp s3://lab-fiap-rm38/instance-need/.ssh/fiap-lab.pem .ssh/ 
  pre_build:
    commands:
      - login=$(aws ecr get-login --region=us-east-1)
      - login="docker login -u AWS -p eyJwYXlsb2FkIjoiQVZhc0s3Y2lqc2dVSjVxRFozUUp6ZCsrSFRvSVRIV1loWnRiQVAwUWM2NWtuVEk0K0xwWGZacEhyYWRKdk1IZmcvakFjWjJuK2NnMXI1Mi9tMjdBRFZvcFZHWjNSclF0WGN6c2ZrbVZoY1FhK2NjNGNnRm9iVHBNVkNNM0hic3pYSWMrc0M4U0pJaThlQm1SMXlwb1RYTnVRcFYyVWk3RnJuN0NjbEQ0MGhwK2lneDlZa2doSDU2UzhxNDZTNnFrVjUrbWxjYkJMNkpFZDA0OUd1MkZLakZEb3FmQWZpR1VvcjgyYlA2RlU2YTBNcGV6QVVRSEUrYUVLZVRrZ2xXcDhlM2NJbm5mb0RuRExCcFA1cWNhTTFjZSt4aUR0SXNLT1RKTkt6b1NUem5ibThLL1VnOUk0U3N5WjI0d21GdlhadDdYYWNHVnZPRHVxM1lOc3d6QTJNeXVuWFpDRWQyeXUxdmxka2d0YmJyYVlyYUxZdDlxdnF5SlFkK0ZPQSttdjg5YzAwMXBMMGxtZi9wRVBacnA5TjlkemcyNjJncitZdnV3M0JiTE5kMTczRGRLa1cwTm1BSmMxaktnQzRxWlpIUVR4elorNGFUVEwrYTg1ZHl5NFFZYmhPWmFNanhlalNQbDkya0hENU14RXQycTU4eU52Z3NNZjkzVmZ6RnBxRC94MjkzTXAzTVM4NFFicVd4cjFsRFlFc1dxZVZ6WkdTaFVMVWNReGFVM0RYenRnbXMxNEdzaW0vTi9CUE50SFFzbmwvMEZLbkt1bHhxL3dIZ2JkY1NpWFJpeGxHaUZzZllDKzJFQWE5MnNtTjlVNTJTNHVYeHZiR0h0ZStod3lwUEVFa0tUTHFXckwyNE1TMktFdTZQTGhyUzZEc2lsaWljTklESFB6U00vMU1hU0wxdmJvR3V3Z1ZxajQ3S2RWRERhNm1pRWlpck1kYThhaGxDandUKzFtR2NwUU10Z1pRM09OeTZwa2NHK1o0LzdtenBNbDc0QTdFOWwzTHAyanZPVjlHWGJ3TThUemxpOGFmMkFxUmFNUVRvcjNTcDR0WStRN3Awa1M2Y2V2SG5uQmRrNFRnY05scEw5UFZ2RmVuNVVMcXNhdkFXMUZWZXcwVEtLWHQ5M1ZUSW1lZy84ZlpGYm56RzV5S05HM3NJWnk5c2VzYlJwNE9vSTFSRHFlMGVGRnpXeW9iaE1HVDRBYW5mcUZENEpweG4vQVZDOE1rd0g3bGpBWTRGOEJuK0grNHh2MTZQOGp0T2V2c0tMdXRHWmhHMVJja1hveXoxeHpQV1JvWjlUVWc2Ly9oak8zYU5pY3ZaeVowemlici96c1pqeXRoUHk5UG80RmRjZWdIamFWV0xYZWlUc3dKZDdLUXV4VEptR3l3dkZJTWErRUZBZFZaWFY0NG1ibk9hM3dGRkpPdTVOdkhtSFlJUTlOOWxEbG55QzNoaFo2OGxHRHhpbGtLd1Fla1hKQXNaYityYXQ3UnFwT2F6OGRlSXJvZVJoU0dQYkFyNUJ0NkR3N2NqSDdDblpuQnNDNENad3hDQlpTdVJPNEdVd3h6K0hKTEJFVlZBaDZrYjZWQmwzdmpLbVRSRVB4WkxFaGhFSnhCNWFxeEgwK1BTajdnYm1zMFJza05MUEtUSVZUNFZqUDgxMTAwOTE4c0FLNzZWVGhPOEIyak1kUnF6WXd2TkhVdHJwV2VsdFFXNzcyY2haMG4vRmxTaVRFSFNVWUdnOEtSMkRXdkZrRURESzc0S3RrVHFpN3JDU1paUVZBR3RNckhwdEJINEhOaUd4UFozQ0hMUWYrRWZhNjF6NGxqOWQ1STY2L1dJZzlPZGl0aXlsOGgvSWJrVT0iLCJkYXRha2V5IjoiQVFFQkFIaHdtMFlhSVNKZVJ0Sm01bjFHNnVxZWVrWHVvWFhQZTVVRmNlOVJxOC8xNHdBQUFINHdmQVlKS29aSWh2Y05BUWNHb0c4d2JRSUJBREJvQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREN3ME9OY2duazdwNjE1ZnpnSUJFSUE3U25uTExlS0Rlb2c5N3JMdmQ5R0pWbFVuZ2JhY2h1MnJlUXFzaXdnNnBtbzhabFVNMnhPRmFLa2VVZDJhdXVzcVNwdWI3L3JjNHJkWHlxST0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MTQ4NjQ3NDN9 https://750498023829.dkr.ecr.us-east-1.amazonaws.com"
      - echo $login | bash      
  build:
    commands:
      - dockerterraform="docker run --rm -w /app  -v $PWD:/app -v $PWD/.aws:/root/.aws -v $PWD/.ssh:/root/.ssh -e PROJ_NAME=$PROJ_NAME $terraformImage"
      - $dockerterraform init 
      - $dockerterraform workspace select $STAGE || $dockerterraform workspace new $STAGE
      - $dockerterraform destroy -var ECR_REGISTRY="${REPOSITORY_URI}" -auto-approve
      - $dockerterraform plan -var ECR_REGISTRY="${REPOSITORY_URI}" -out plan.out
      - $dockerterraform apply -var ECR_REGISTRY="${REPOSITORY_URI}" -auto-approve
      - elb=$($dockerterraform output elb_public)
      - echo $elb >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt
    - plan.out
